### ISSUE TITLE
"import * as alias" also importing "default"

### ISSUE THREAD

**Issue by fhelwanger** [erikras/ducks-modular-redux#13]
First of all, I really like the "ducks" approach, thanks!

But there is something I've noticed. In the README, it says:

> You can still do:
> 
> ``` js
> import * as widgetActions from './ducks/widgets';
> ```
> 
> ...and it will only import the action creators, ready to be passed to bindActionCreators().

But actually, it also import `default` into `widgetActions`. You can `console.log(widgetActions.default)` anywhere in the Widgets container of [react-redux-universal-hot-example](https://github.com/erikras/react-redux-universal-hot-example/) to see it.

Maybe it's a minor detail, but I prefer to enum every action creator to avoid binding `default`.

**Comment by erikras** [comment]
Hmm... This was not the case, before. Maybe Babel changed.

**Comment by fhelwanger** [comment]
I took a look at the ES2015 spec, it seems to me that this kind of import shouldn't be importing `default`.

Check, http://www.ecma-international.org/ecma-262/6.0/#sec-getexportednames, item 7. d. i.

Am I right? Maybe it's a bug (or feature :smile:) in Babel?

**Comment by fhelwanger** [comment]
Sorry, I looked at it again, it seems that the line I pointed was for the following situation:

```js
export * from 'mod';
```

In this case, it wouldn't export `default` from another module.

I really don't what **should** be the behavior. Can't find a direct answer to it anywhere.

**Comment by simensen** [comment]
@fhelwanger I just figured out how to do this and you can try it out as well, though it might not be ideal (assuming it actually omits `default` for you...):

```
// will include default in export
import * as mod from 'mod'
export mod
```

```
// should omit default from export
import * as mod from 'mod'
export {mod}
```

**Comment by fhelwanger** [comment]
Thanks @simensen!

But actually, I wouldn't do this export only to omit default.

I still prefer to just name each action creator to import on my components, like this:

```js
import { act1, act2 } from 'ducks-module';
```

Instead of ```import * as actions...```

**Comment by simensen** [comment]
@fhelwanger in my tests last night i found that it wasn't omitting default anyway. :-/ which was a bummer. oh well! i changed around how i was building my module anyway so i didn't need it anymore. :)

**Comment by chapati23** [comment]
Why don't we just bundle the actions in a dedicated object? No more `import * as actions` magic would be necessary, just a simple `import {actions} from module`

```
export const actions = {
    toggleSomething: function toggleSomething() {
        return { actionTypes.TOGGLE_SOMETHING }
    }
}
```

**Comment by lucascosta** [comment]
Shouldn't this be updated in the docs? It's kind of misleading...
