### ISSUE TITLE
The name

### ISSUE THREAD

**Issue by qnm** [erikras/ducks-modular-redux#14]
I love ducks as much as the next person, but really - this proposal is about Constants, Actions and Reducers. CARs! KA-CHOW!

![](https://upload.wikimedia.org/wikipedia/en/2/27/LightningMcQueen.jpg)

(The concept is awesome - thanks for you work, @erikras!)

**Comment by erikras** [comment]
LOL. Good one.

**Comment by andrew-codes** [comment]
Just found this. We utilize a very similar concept at VersionOne and came to name them state atoms. A state atom essentially is a directory level module exporting a Reducer, Selectors, Action Creators, and Actions. We developed a standard directory structure for these that make them pretty easy to stamp out. State atoms can interact and are composed to in different ways to create pages within our product. Finding this, its similarities and this name issue, I thought I would share.
