### ISSUE TITLE
Why should "npm-module-or-app/reducer/" be prepended when defining action types?

### ISSUE THREAD

**Issue by timche** [erikras/ducks-modular-redux#29]
Why can't I just write simply i.e. `const LOAD = 'LOAD_WIDGET';`?

Thanks :)

**Comment by elyobo** [comment]
I assumed it was to make your life easier when debugging; when you're dealing with a small app just seeing 'LOAD_WIDGET' may be clear enough, but in a complex application with a lot of actions (and reusing npm modules which generate their own actions) it will make it much easier to understand where the code related to an action is.

Meanwhile the overhead (having to type in a longer action name one time) is pretty small, as everywhere else you just type 'LOAD'.

**Comment by timche** [comment]
Thanks for your explanation :)

**Comment by timche** [comment]
One more thing, sorry: So what's the reason then to write `npm-module-or-app/` before `widgets/LOAD`?

Are there actually 3rd party libraries for Redux that will trigger actions?

**Comment by elyobo** [comment]
No idea whether there are public third parties modules that use the ducks pattern + redux, but internally we have shared components between some of our apps and so indicating the module/app in the action does help us to distinguish between the action sources.  Again, not a massive benefit, but there's no downside and no effort to implement, so I'm all for it :)

**Comment by erikras** [comment]
As the author of one such library, [`redux-form`](https://github.com/erikras/redux-form), I would say "Yes." :-)

**Comment by elyobo** [comment]
As a user of redux-form, I probably should have known that :D
