### ISSUE TITLE
Best practices to combine different ducks results

### ISSUE THREAD

**Issue by dariooddenino** [erikras/ducks-modular-redux#3]
Hi, 
I have a duck that loads projects and one that loads users from a server.
I'd like to write a third duck that would process stats combining info from projects and users.

Should I dispatch an action from my component as soon as projects and users are loaded? 

Thanks for your work!

**Comment by erikras** [comment]
> Should I dispatch an action from my component as soon as projects and users are loaded?

Yes, I think that's the best way.
