### ISSUE TITLE
Usage of the term "ducks"

### ISSUE THREAD

**Issue by arahansen** [erikras/ducks-modular-redux#30]
Not sure I agree with using the term "ducks" for what you are proposing. When I first came across the term, I related it to "duck typing" and my confusion compounded for quite some time trying to figure out what people were referencing.

It wasn't until someone just happened to link to this repo that my confusion was cleared up.

That being said, I do find merit in the proposal itself. I've started coming to a similar conclusion myself 😄

**Comment by michaelghinrichs** [comment]
I agree, `ducks` is a very confusing term. I like using something more generic like `module.js`

**Comment by chasm** [comment]
Or call it "dux" to make it clearer?

**Comment by erikras** [comment]
[Gems](https://rubygems.org) and [jars](https://en.wikipedia.org/wiki/JAR_(file_format)) and [beans](https://en.wikipedia.org/wiki/JavaBeans) and [casks](https://caskroom.github.io) and [wars](https://en.wikipedia.org/wiki/WAR_(file_format)), and even [zip](https://en.wikipedia.org/wiki/Zip_(file_format)), are all "very confusing terms" that have other meanings, too, but eventually you learn the new definition.

You're free to call them whatever you like, of course. Geese, maybe?

**Comment by chasm** [comment]
I'm going with turds, then.

**Comment by eezing** [comment]
I say keep it "ducks". It's memorable and verbally descriptive within the context of redux.

**Comment by andrew-codes** [comment]
Maybe I posted this in the wrong issue, so I will link and post it here also (#14)

We utilize a very similar concept at VersionOne and came to name them state atoms. A state atom essentially is a directory level module exporting a Reducer, Selectors, Action Creators, and Actions. We developed a standard directory structure for these that make them pretty easy to stamp out. State atoms can interact and are composed to in different ways to create pages within our product. Finding this, its similarities and this name issue, I thought I would share.

**Comment by danludwig** [comment]
> Gems and jars and beans and casks and wars, and even zip, are all "very confusing terms" that have other meanings, too, but eventually you learn the new definition.

So I get this for gems, beans, casks, and zip. Maybe not for jars and wars, since they actually have letters that turn into words (Java, Web, and ARchive).

If you plan on calling them ducks, and you're keyboard skills are not excellent, practice to make sure you don't accidentally type `i` when you mean `u` :/

Love the pattern. The name, not so much.

**Comment by abustamam** [comment]
Case in point:



<img width="237" alt="slack" src="https://cloud.githubusercontent.com/assets/3794984/17574231/5dcee6c8-5f14-11e6-95af-fe8f99c1b623.png">

**Comment by danludwig** [comment]
:point_up: priceless

**Comment by danludwig** [comment]
I also hadnt realized the f key is right next to the d as well. You could type a profanity laden sentence fragment by just mistyping `ducks` three times.

**Comment by bobisme** [comment]
So... gems, beans, casks, and zip are all package(ish) file types.  Ducks is really only a pattern.  I'm fine with the name, just not using a "ducks" directory.  Why not just "reducers" so

```javascript
// this
import * as reducers from './ducks/index';
// woud become
import * as reducers from './reducers/index';
```

...?

**Comment by abustamam** [comment]
@bobisme Erik seems to use the directory, "modules" in his universal project:

https://github.com/erikras/react-redux-universal-hot-example

At the end of the day, the directories in the projects you're working on can be named whatever you like; "ducks," "bucks," "super-special-awesome-redux-stuff," whatever works for your team. It's just a concept/pattern, and can boil down to just code convention that you set up with your team (like using the `.jsx` extension)

**Comment by williamoliveira** [comment]
A related issue:
"ducks" it works fine for folders, but what to name a single file, duck.js? it breaks the pun

**Comment by natchiketa** [comment]
When I was first reading about ducks, since the point was to make the actions/reducers easier to manage by keeping them together, I thought the reference was about "having your ducks in a row". At first I groaned at myself for not getting the 'dux' thing, but now I propose that this is an additional  reason to keep it that way.

I mean yeah, there's duck typing, but then there's also [rubber duck debugging](https://en.wikipedia.org/wiki/Rubber_duck_debugging), which is **yet another *completely* different** thing. So I say there's room for more than one kind of 🦆.
