### ISSUE TITLE
Shorten constant definitions?

### ISSUE THREAD

**Issue by wmertens** [erikras/ducks-modular-redux#31]
So I wonder why you don't write
```
const p = 'my-app/widgets/';
const LOAD   = p + 'LOAD';
const CREATE = p + 'CREATE';
const UPDATE = p + 'UPDATE';
const REMOVE = `${p}REMOVE`; // also possible
```
instead of
```
const LOAD   = 'my-app/widgets/LOAD';
const CREATE = 'my-app/widgets/CREATE';
const UPDATE = 'my-app/widgets/UPDATE';
const REMOVE = 'my-app/widgets/REMOVE';
```

I guess it's just a matter of preference, or is there more to it?

**Comment by erikras** [comment]
Sure. That's what's great about this language: its flexibility. I do think that @gaearon was right in his initial launch of Redux with his message of, (I'm paraphrasing) "_Calm down people!_ You have more important things to worry about than avoiding string constants!", so I tend to not let the action definitions at the top of a duck bother me too much.

To my present-day (who knows about tomorrow?) sensibilities, I think something like this looks pretty nice, especially if you had a lot of actions:
```js
const createAction = name => `my-app/widgets/${name}`;
const LOAD   = createAction('LOAD');
const CREATE = createAction('CREATE');
const UPDATE = createAction('UPDATE');
const REMOVE = createAction('REMOVE');
```
It would minify nicely, at least.

But yes, just a matter of preference. How you build the strings is outside the scope of the Ducks spec.

**Comment by wmertens** [comment]
:+1: thanks for clarifying.
