### ISSUE TITLE
Translations?

### ISSUE THREAD

**Issue by JisuPark** [erikras/ducks-modular-redux#35]
Hello @erikras !

Thank you for "ducks". quack! quack!

Recently, I am applying "ducks" to refine my redux app.

While doing it, I translated Readme.md in [Korean](https://github.com/JisuPark/ducks-modular-redux/blob/master/README.md).

If you are okay I want to add **Translation** section to navigate people who wants it.

Thanks.

**Comment by sesm** [comment]
Not @erikras here, but I think you should just send a Pull Request.

**Comment by JisuPark** [comment]
@sesm Oh I see, Thanks!

**Comment by erikras** [comment]
Merged.
