### ISSUE TITLE
Module Connectors

### ISSUE THREAD

**Issue by lucascosta** [erikras/ducks-modular-redux#37]
Hi Erik! I think **Ducks** is awesome, but what if we moved the `connect` logic from the components? It seems to me that this is more of a Module responsibility, since it's coupled to the reducer logic.

I suggest `connector` functions exported from the Modules, which can then be used as a simplistc decorator in the Components. I have made a simple commit on the example showing what I mean, would you take a minute to have a look?
https://github.com/lucascosta/react-redux-universal-hot-example/commit/b6bf96b84a303c20b6a59dd9de27475e8cfb9737

This approach enables exclusive presentational concern on the components, and prevents code duplication if for example you want to A/B test different UI components using the same logic.
What do think?

**Comment by raythree** [comment]
I agree that Components should not need to be importing from redux. So far I've stayed with the mapDispatchToProps and mapStateToProps usage of connect, and have found using them in that way is useful, especially when a Container has multiple Components. My most recent attempt at doing this with minimum boilerplate is [this](https://github.com/raythree/redux-action-binder).
