### ISSUE TITLE
Usage differences in readme

### ISSUE THREAD

**Issue by BrainCrumbz** [erikras/ducks-modular-redux#4]
Hello. Thanks for this proposal you shared, we just started documenting on Redux and this really makes sense! 
There's something not completely clear to me in [Usage section](https://github.com/erikras/ducks-modular-redux#usage): 

 1. In order to import reducers, there's an `import * as reducers from './ducks/index';`. What's in that `index.js`? 
 1. (probably related to previous one) How would you import all reducers in order to combine them, as seen usually in Redux tutorials?
 1. (this is more about ES6) In order to import action creators there's `import * as widgetActions from './ducks/widgets';`. Is that *skipping* over the default export and just grabbing the rest?

Thanks for your time

**Comment by erikras** [comment]
1. `export widgets from './widgets'; export auth from './auth';` However, I have since migrated to the idea that it is best to do the `combineReducers` call in a [`ducks/reducer.js` file](https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/ducks/reducer.js).
2. You're correct. See 1.
3. Yes. I was half-surprised at this behavior, but yes, `import * from` skips over the `export default`.

**Comment by BrainCrumbz** [comment]
Thanks for reply.
What I dislike of this particular approach in *ducks/reducer.js* is that it has to be manually modified (i.e. you have to remember to do that) everytime a new reducers is born. Apart from being easy to miss, it goes against design principles like Open/closed principle, and it's a pity given the great thoughts behind e.g. Redux and Ducks.

Ideally, one should be free to structure its project folders and files how it best fits for its purposes, and e.g. not be forced by the way *import ** works. So e.g. with Ducks one can put its reducers in a file with actions, etc Someone else might split things in a *reducers* folder, *actions* folder, etc. 

Thinking about how we face similar issues in C#, isn't there a way to *mark* all reducers (and all action creators as well), keep them wherever they happen to be defined, and let *ducks/reducer.js* collect them? In C# you would do that by means of reflection, e.g. with a *marker Interface*, or through *Attributes*.
With TypeScript there are *Interfaces*, don't know if you can reflect over them. With experimental ES7 there are *Annotations*, but again don't know if that can be used to the purpose (I got that they are mainly a way to apply higher-order functions).

**Comment by erikras** [comment]
As far as I know, there is no way to `import * from [some-dir]` in javascript, [at least in Babel](http://babeljs.io/docs/usage/modules/). It would certainly be more elegant if you could.

**Comment by BrainCrumbz** [comment]
And not even some more complex/funky wildcard as `import *Reducer as reducers from *`, so that you could have a naming convention and import anything that was exported as *xxxReducer* from any JS file. Thanks for clarifying, I guess we can close this issue if you agree.

**Comment by erikras** [comment]
You had some great input, but I think the language just isn't there yet.

It's possible to hack the system with "require hooks", e.g. [`node-hook`](https://github.com/bahmutov/node-hook), but that's non-standard and probably should not be relied upon for best practices.

**Comment by BrainCrumbz** [comment]
Oops, sorry for resurrecting, it just came to my mind. What about an approach like the following (kind of pseudo-code)?

```js
// Idea: build up a map of all named exports, each one mapped to its name as key. (Maybe too much overhead?)
var allExports = {
  ...require('./auth'),
  ...require('./counter'),
  ...require('redux-form'),
  ...require('./info'),
  ...require('./widgets'),
};

// no more changes beyond this line

import { combineReducers } from 'redux';

function reducerConventionByName(name) {
  return (name.indexOf('Reducer') > -1);  // or > 0, or use regex
}

var allReducers = Object.keys(allExports)
  .filter(reducerConventionByName)
  .map(key => allExports[key]);

export default combineReducers(allReducers);
```

**Comment by erikras** [comment]
And the value you get from this is.....?

You `export default` everything from your duck as a hash, and then this selects only the functions that end in `Reducer`?

**Comment by BrainCrumbz** [comment]
Currently, for every duck created you need to add an import similar to `import auth from './auth';` and then a reference to `auth` in `combineReducers()`. 
With an approach similar to this one, you just need to add a require similar to `require('./auth')`. It seems (a little) less repetitive work.

Please forgive the actual pseudo-code, don't take that literally: in order for that to work, reducers should be named exports (not default exports as they're now) and should follow some naming convention, e.g. end their name in *Reducer*. As I said, that is to test the value about the idea, actual implementation can be wrong.

**Comment by despairblue** [comment]
@erikras what do you think about this:

```javascript
// ducks/widget1.js

const LOAD   = 'my-app/widgets/LOAD';
const CREATE = 'my-app/widgets/CREATE';
const UPDATE = 'my-app/widgets/UPDATE';
const REMOVE = 'my-app/widgets/REMOVE';

export default function reducer(state = {}, action = {}) {
  switch (action.type) {
    // do reducer stuff
    default: return state;
  }
}

export const actionCreators = {
  loadWidgets() {
    return { type: LOAD };
  },

  createWidget(widget) {
    return { type: CREATE, widget };
  },

  updateWidget(widget) {
    return { type: UPDATE, widget };
  },

  removeWidget(widget) {
    return { type: REMOVE, widget };
  }
}
```

```javascript
// ducks/index.js

import widget1, {actionCreators as widget1ActionCreators} from './widget1'
import widget2, {actionCreators as widget2ActionCreators} from './widget2'

export default {
  widget1,
  widget2
}

export const actionCreators = {
  ...widget1ActionCreators,
  ...widget2ActionCreators
}
```

```javascript
// App.js

import reducers, {actionCreators} from './ducks'

// ...
```

**Comment by erikras** [comment]
That would mean that no two ducks could have an action creator with the same name, would it not? They'd all have to be in the `verbObject` form, like `updateWidget`.

**Comment by despairblue** [comment]
Right, that would need to be handled in `index.js`, just like it would need to be handled where ever

```javascript
import * as widget1Actions from './ducks/widget1'
import * as widget2Actions from './ducks/widget2'

bindActionCreators({
  ...widget1Actions
  ...widget2Actions
}, dispatch);
```

is right now.
