### ISSUE TITLE
Any advantage to using this pattern?

### ISSUE THREAD

**Issue by joetidee** [erikras/ducks-modular-redux#49]
In widjets.js, instead of:

```
const LOAD   = 'my-app/widgets/LOAD';
const CREATE = 'my-app/widgets/CREATE';
const UPDATE = 'my-app/widgets/UPDATE';
const REMOVE = 'my-app/widgets/REMOVE';
```

do...

```
import * as ATYPES from './my-app/widgets';
...
export function loadWidgets() {
  return { type: ATYPES.LOAD };
}
```

**Comment by HugoMcPhee** [comment]
I think the strings in first snippet aren't actual paths but just names (they aren't importing anything).

**Comment by notrab** [comment]
That's right @HugoMcPhee - They're set constants for ACTIONS.

They're namespaced to prevent multiple reducer triggers as your application size increases.
