### ISSUE TITLE
Change the last example of the Update section

### ISSUE THREAD

**Issue by tbassetto** [erikras/ducks-modular-redux#5]
When you want to export something other than an action creator, you have to enumerate the action creators that you want. The example in the README is the following:

```js
import {create, update, remove, increment} as widgetActions from './ducks/widgets';
// ...
bindActionCreators({create, update, remove, increment}, dispatch);
```

But unless I am missing something, it's not valid (tested with the latest version of babel). The two following versions are valid though:

```js
import {create, update, remove, increment} from './ducks/widgets';
// ...
bindActionCreators({create, update, remove, increment}, dispatch);
```

```js
import {create, update, remove, increment} from './ducks/widgets';
const widgetActions = {create, update, remove, increment};
// ...
bindActionCreators(widgetActions, dispatch);
```

Do you confirm?

**Comment by erikras** [comment]
You are absolutely right. Thanks, @tbassetto.
