### ISSUE TITLE
Object orientation

### ISSUE THREAD

**Issue by hcschuetz** [erikras/ducks-modular-redux#6]
Erik,

I recently stumbled over similar problems and thought of a solution.  It turns out that there are some commonalities with your approach but also differences.  In particular I'd suggest to use classes where you suggest to use modules.  (And I don't have such a precise specification yet as you have it.)

See below what I wrote.  What do you think?

Heribert

Object-Oriented State Structure
-------------------------------

The structure of the state is not described explicitly anywhere.  It's
just transformed by the reducers and read by React components.  The
reason for this is that it is represented as plain untyped JSON data.
So functionality concerning the state goes to reducers and React
components, which in turn may have to deal with different parts of the
state.  This easily leads to spaghetti code.

Consider a frequent case in business-software development: We need a new
field and code dealing with this field.  (This is much more frequent
than "architectural" changes, at least after the initial development
phase.)  It would be nice if we did not have to change code in lots of
different places.  Ideally all the relevant changes would happen in a
single place.  (Yes, there is a trade-off with other considerations, but
it looks like my consideration has not yet been taken into account in
the published "best practices" for redux such as the tutorial.)

Actually with redux one can use instances of specific classes to
represent the state.  I think one should.

This also allows to put core transformation functionality into methods
of these classes.  (Notice that these methods must still be purely
functional in that they do not modify "this" but rather return a
transformed version of "this".)  This would bring back the advantages of
encapsulation and object-oriented programming and can be used to avoid
spaghetti code.

We might use a convention that state classes provide (in addition to any
class-specific action) a method "reduce(action)".  Some standard
utilities might make use of this convention.

State classes might also provide utilities for the React components,
including relevant action creators.

**Comment by erikras** [comment]
So the data _would_ be stored under `this`, but your mutators/setters would return a clone of the entire instance with the specific elements modified? I'm really not seeing how this is that much superior to the standard reducer structure, which still has to clone the whole state object with modifications. Are you hoping to make gains with inheritance with similarly shaped objects?

In general, whenever I have decided to do something in a more functional way, rather than OO, it has paid dividends, so I'm not convinced that introducing OO into the beautifully functional Redux architecture is the right thing to do, but there could definitely be some advantages. The other nice thing about Redux is that it leaves all the state controlling implementation details up to the developer.

**Comment by hcschuetz** [comment]
> So the data *would* be stored under `this`, but your mutators/setters would return a clone of the entire instance with the specific elements modified?

Yes.  (But notice that there is no need to clone unmodified properties.  These can just be re-used in the clone of "this".  That is, shallow cloning suffices as in any other Redux reducer.)

> I'm really not seeing how this is that much superior to the standard reducer structure, which still has to clone the whole state object with modifications.

My point is not about cloning.  It's about encapsulation and code locality.  See below.

> Are you hoping to make gains with inheritance with similarly shaped objects?

No, but that might turn out as a nice bonus.

> In general, whenever I have decided to do something in a more functional way, rather than OO, it has paid dividends, so I'm not convinced that introducing OO into the beautifully functional Redux architecture is the right thing to do, but there could definitely be some advantages.

There seems to be a widespread misconception that functional and OO programming contradict each other.  Well, in practice that's often true: Popular OO languages like C++ and Java are basically imperative rather than functional.  But in theory (and in my proposal) OO and functional programming are independent concepts.

Decades ago people used imperative languages such as ALGOL, PASCAL and C, that were neither functional nor OO.  To overcome problems with these languages, several concepts have been developed, including functional and OO programming.
- Functional programming avoids mutation and thus several mutation-related problems.
- OO programming is about combining data structures with operations on these structures.  And about encapsulation, i.e. hiding data structures and other implementation details behind defined interfaces in abstract data types.  This allows you to change implementation details locally as long as your interfaces remain the same.  This also encourages you to put related code and data structures next to each other rather than dispersed over the code base.

As I said above, mainstream OO languages happen to be imperative rather than functional, but there is nothing that prevents you from using an OO and functional programming style.    (And actually the OO languages C++ and Java are slowly moving towards better functional-programming support, while JS, which perhaps has the best functional-programming support among mainstream languages, moves towards better OO support.)

My point about Ducks is essentially:  Why introduce a new encapsulation mechanism when we already have ES6 classes to achieve the same?  I'm not saying we get something better than Ducks from classes, but we can simply reuse an existing standard concept here.

Having said this, I must admit that JS/ES6 is not very good at actually technically hiding implementation details.  It is still possible to access implementation details from the outside (unless you spend quite some effort on blocking access).  It's a matter of convention to only use the "official" API of a class.  But I guess the same is true for Ducks.

(And don't get me wrong.  I feel "on your side" since we both want to solve the problem of related code being dispersed over the code base, which seems to be largely ignored in the Redux community.)

> The other nice thing about Redux is that it leaves all the state controlling implementation details up to the developer.

That would remain the same with my suggestion.

**Comment by hcschuetz** [comment]
oops, hit the wrong button...

**Comment by erikras** [comment]
@gaearon, any thoughts?

**Comment by gaearon** [comment]
I'm not sure what is being proposed. The only meaningful way to discuss this is to port non-trivial example (e.g. `todomvc`) from Redux to this approach and compare.

Please keep in mind that Redux has some explicit goals such as the ability to record all actions, serialize them, and later replay them. This is something that often gets lost in attempts to OOP-ize Redux.

Somewhat relevant:

https://github.com/rackt/redux/issues/437
https://github.com/rackt/redux/issues/628
https://github.com/rackt/redux/issues/780
http://rackt.github.io/redux/docs/recipes/ReducingBoilerplate.html

**Comment by hcschuetz** [comment]
@gaearon, yes, having an example makes sense.

So I've ported `todomvc` from the redux repository to OO style: [hcschuetz/todomvc-redux-oo](https://github.com/hcschuetz/todomvc-redux-oo).  There's still too much boilerplate and I will have to introduce utilities to minimize that.  But I'm afraid that it will not get around to do this in the next days.  However, the current code should already give the core idea.

No changes to redux are needed.

As opposed to some of the links above, I'm not converting actions into class instances.  Actions keep their current format (JSON-style objects with a `type` property).  I am rather representing the state using class instances.  And action creators and reducers become methods of these classes.

There is, however, one change to actions for nested state objects:  I'm wrapping actions intended for inner state objects in "navigation actions" for outer state objects, e.g.:
```
{type: "UPDATE_TODO", id: 7, subAction: {type: "SET_TEXT", text: "Use OO"}}
```

And to avoid that this comment is completely unrelated to the Ducks repository:  Consider you want to add another property to todo items.  Then all you need to implement for the business logic goes to a single file, `state/TodoItem.js` and will not be dispersed over the code base.  And that's why I wrote that using classes can solve the same kind of problem as Ducks.

I'm closing this issue because further discussion on this topic should better go to [hcschuetz/todomvc-redux-oo](https://github.com/hcschuetz/todomvc-redux-oo).

**Comment by gaearon** [comment]
Thanks!

Personally I don't think putting action creators together with reducer is always right. (This was my complaint with Ducks too, but some people like it this way so I don't blame them. :-)

Technically as your app grows you'll find that some reducer from distant parts of the app want to handle the same action. Putting them together in a single class is enforcing unnecessary constraints that may puzzle the developers later when they need to scale the app.

Another reason I don't think using classes for state is right is that it makes non-trivial reducer composition and higher order patterns more difficult and verbose. Consider [Implementing Todo History recipe](rackt.github.io/redux/docs/recipes/ImplementingUndoHistory.html)—it's so easy with functions, but you'll get a lot more boilerplate with classes.

I think if you like classes you should just stick with Flux. There's even [ReduceStore](https://facebook.github.io/flux/docs/flux-utils.html#reducestore-t) which looks similar to what you propose.

**Comment by hcschuetz** [comment]
I'm continuing this discussion [here](https://github.com/hcschuetz/todomvc-redux-oo/issues/1) because it has become off-topic for Ducks.
