### ISSUE TITLE
Naming convention when extracting case reducers to prevent conflicting with action creators? 

### ISSUE THREAD

**Issue by tomalexhughes** [erikras/ducks-modular-redux#69]
I'm attempting to extract my reducing cases to individual functions within the 'duck' file, similar to [this section of the Redux documentation](https://redux.js.org/docs/recipes/reducers/RefactoringReducersExample.html#extracting-case-reducers).

My current issue is that keeping my action creators in the same 'duck' file is causing naming conflicts currently, for example:

- I have the action RESET_QUEUE.
- I have the action creator function 'resetQueue'.
- I have named my reducing function 'resetQueue' also.

My only current solution is to prefix the reducing function, i.e. have the action creator 'resetQueue' and the reducing function 'performResetQueue' or 'performQueueReset'.

Is there a convention set when using Ducks as to what an action creator, and the reducing function should be named (if the reducing function is split from the switch statement). Or is it a better practice to not split the reducing functions from the reducer in the first place?

**Comment by aij** [comment]
I think you're free to name your helper functions as you see fit. They're private to the module anyway, so their name, existence, or lack of existence shouldn't affect anyone using the module.

If you're going to make each case a separate function, you could even throw them in an object with each function named after the action type it handles. That way you don't need to translate from one set of names to the other in the reducer.

For example, (following the README) something like

```
const reducers = {
  [LOAD]: (state, action) => {
    ...
  },
  [CREATE]: (state, action) => { ... },
  [UPDATE]: (state, action) => { ... },
  [REMOVE]: (state, action) =>  { ... },
}

export default function reducer(state = {}, action = {}) {
  const actionHandler = reducers[action.type];
  return actionHandler ? actionHandler(state, action) : state;
}
```

**Comment by tomalexhughes** [comment]
Thanks for that! Following that suggestion, and also using the [Generating Action Creators](https://github.com/reactjs/redux/blob/master/docs/recipes/ReducingBoilerplate.md#generating-action-creators) section from the Redux doc's I've managed to slim one of my duck files down from 250 lines to 180.

Cheers.
