### ISSUE TITLE
It would be nice to provide some example

### ISSUE THREAD

**Issue by jmarceli** [erikras/ducks-modular-redux#7]
Hi,
I found this "project" while learning React and Redux. It would be really nice to have some kind of working example module built with "Ducks" approach.
Something which could be downloaded and used in my own application as a component. Even simple Counter (https://github.com/rackt/redux/tree/master/examples/counter) rewritten in Ducks way would be helpful.

**Comment by erikras** [comment]
[React Redux Universal Hot Example](https://github.com/erikras/react-redux-universal-hot-example) uses ducks.

**Comment by jmarceli** [comment]
OK. Thanks.
