### ISSUE TITLE
Writing my first Duck module

### ISSUE THREAD

**Issue by nicolabortignon** [erikras/ducks-modular-redux#8]
Ok, I've been smashing my head against this for the last days. @erikras  please help out.

I'm using the boiler plate, and i'm trying to start writing my redux. Reading the idea behind ducks, you sort of bought me into it, so why not trying.

I promise I'll write a DUCKS for newbies if I'll managed to understand how to implement one myself.

So, let's start with what I have in mind.

I'm creating a user onboarding form. One of those 3-4 steps forms that the user fills in in order to register on a website.
I've done the UI. 
A Container: https://github.com/TracklistMe/ReactClient/blob/master/src/containers/Landing/Landing.js 
with a major component:  https://github.com/TracklistMe/ReactClient/blob/master/src/components/Onboarding/BetaOnboardingForm.js

(now let's not focus on how poorly I designed the Component, let's pretend one day I'm going to modularize it better).
The page is live at tracklist.me

Now, my redux state shape should be something like
```javascript
{
 currentStep:  string
 user:  object
}
```

at each step I'm collecting more info about the user, verify them server side, and then move to the next step client side.
The server side api are all done. And they are a combination of posts/gets/puts. 

Now, let's start really basic. Let's create the part of the ducks that manage the first step, that is:

Tell me your email. If it does't exist, I'll save in the db, and let you move on to step2. If does exist, I'll let you know and move to stepSignIn (where you can insert your password to sign in).
For the sake of this learning experience let's pretend thats all i want to implement.

The actions that I have identified are: 
```javascript
REQUEST_EMAIL_REGISTRATION
RECEIVE_EMAIL_REGISTRATION_CONFIRMATION
RECEIVE_ERROR_FROM_EMAIL_REGISTRATION
```

The call to the api endpoint is 

```javascript
export function registerEmail(userData) {
promise: (client) => client.post('/email/', {
      data: userData
    })
}
```

So far I came up with this... that is more of a collage between the standard redux guide and the widget implementation in the boilerplate.

Not quite sure where to plugin the api call

```javascript
const REQUEST_EMAIL_REGISTRATION = 'SEND_REQUEST_TO_REGISTER_EMAIL';
const RECEIVE_EMAIL_REGISTRATION_CONFIRMATION = 'EMAIL_REGISTERED';

const initialState = {
  currentPhase: PAGE_OPENED,
  user: {}
};

export default function earlyUser(state = initialState, action = {}) {
  switch (action.type) {
    case REQUEST_EMAIL_REGISTRATION:
      return Object.assign({}, state, {
        currentPhase: REQUEST_EMAIL_REGISTRATION
      });
    case RECEIVE_EMAIL_REGISTRATION_CONFIRMATION:
      return Object.assign({}, state, {
        currentPhase: RECEIVE_EMAIL_REGISTRATION_CONFIRMATION,
         items: action.user,
         lastUpdated: action.receivedAt
      });
    default:
      return state;
  }
}

// The actions for register an email

export function emailRegistrationRequest(email) {
  return {
    type: REQUEST_EMAIL_REGISTRATION,
    email
  };
}


export function emailRegistationConfirmed(json) {
  return {
    type: RECEIVE_EMAIL_REGISTRATION_CONFIRMATION,
    user: json.data,
    receivedAt: Date.now()
  };
}
```

Thank you in advance!

**Comment by erikras** [comment]
A few things:

1. I normally name my actions `X`, `X_SUCCESS`, `X_FAILURE`, and make their variable names and string values identical. It's a style preference, but I think it's probably good practice.
2. You broke [the first rule](https://github.com/erikras/ducks-modular-redux#rules) of the Duck Spec! :rage: What is this, _Fight Club_? :stuck_out_tongue:
3. The primary thing that you have missed is the magic of [`clientMiddleware.js`](https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/redux/middleware/clientMiddleware.js), which lets you specify three action types (request, success, and failure) with your action, and a promise. The middleware will then:
  1. dispatch the request action
  2. call your promise function
  3. dispatch either success with a `result` key or failure with an `error` key.

Here's how I would write your duck.
```js
const EMAIL_REGISTRATION = 'EMAIL_REGISTRATION';
const EMAIL_REGISTRATION_SUCCESS = 'EMAIL_REGISTRATION_SUCCESS';
const EMAIL_REGISTRATION_FAILURE = 'EMAIL_REGISTRATION_FAILURE';

const initialState = {
  phase: 0,   // I would just make this what "page" you are on in the multistep process
  user: null  // Better null or undefined than {} if no data
}

// you didn't name this reducer like the spec says!!
export default function reducer(state = initialState, action = {}) {
  switch (action.type) {
    case EMAIL_REGISTRATION:
      return {
        ...state, // destructuring is AWESOME. Learn it. I much prefer it to
                  // Object.assign, which babel transpiles it down to.
        registering: true // I prefer booleans to keeping action types in state.
                          // booleans also make it easy to do
                          // {registering && <div className="indicator"/>} in jsx
      };
    case EMAIL_REGISTRATION_SUCCESS:
      return {
        ...state,
        user: action.result, // result is set by client middleware
        phase: 1,            // shows this step is done and ready for next step
        registering: false   // hide indicator
      };
    case EMAIL_REGISTRATION_FAILURE:
      return {
        ...state,
        registering: false,             // hide indicator
        registrationError: action.error // error is set by client middleware
      };
    default:
      return state;
  }
}

export function registerEmail(data) {
  return {
    types: [EMAIL_REGISTRATION, EMAIL_REGISTRATION_SUCCESS, EMAIL_REGISTRATION_FAILURE],
    promise: client => client.post('/email/', {data})
  };
}
```

**Comment by nicolabortignon** [comment]
@erikras this is amazing! Really neat. I'll already implemented your redux, now i'll connect with the container and sub components.
For now really thank you so much. I may coming back to this Issue just to check with you I implemented the rest in the proper way. Keep it close, no need to reopen.

Thanks again, and thanks also for the amazing job you are doing with the boilerplate.
(is there any way to back your work? )

**Comment by erikras** [comment]
You're welcome. Come back any time.

Both projects have a little donate button at the top of the readme, amongst the badges.

**Comment by erikras** [comment]
Thank you _very_ much for your donation, @nicolabortignon. :+1:  :+1:

**Comment by nicolabortignon** [comment]
No problem at all, you deserve it! 

Question:  I'm writing the API with a pretty strong semantic use of the errorCode.  Ie. a 404 is different from a 409. 
I see that the action.error returns just the JSON, but not the errorCode.
Is there a way to access that?

**Comment by erikras** [comment]
1. The http code _must_ be available [here](https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/helpers/ApiClient.js#L40). Check the `superagent` docs.
2. That doesn't make any sense to me. You can really call `setIsLabel(); registerUser();` (literally contiguously like that, not via event listeners) and see `registering` before `updating label` in the console?? I was under the impression that redux dispatching was synchronous. There's nothing stopping you from writing the `setIsLabel()` in the `{types, promise}` format with dummy values (`undefined` might work) for the success and failure types.

**Comment by nicolabortignon** [comment]
1. I'm not quite sure how I can access the superAgent object from within one action in the reducer.
What I need to do is  on the action  EMAIL_REGISTRAION_FAIL have a switch on the type of http error. action and action.error don't have that information.

2. You are right, the problem is that I was calling setIsLabel() and registerUser() from the JSX. the two calls are syncronous, but the way the store is set and notified to the view it is not. So by the time I was calling registerUser in the JSX the store in the JSX was still as it was before the call of setIsLabel().
I need to move the two calls in the reducer, so the store will be update synchronously. (or at least this is my understanding :D )

**Comment by erikras** [comment]
No, I meant to modify your `ApiClient.js` to look at the response `status`. Change [this](https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/helpers/ApiClient.js#L40) to:
```js
request.end((err, {body, status} = {}) =>
  err ? reject({
    error: body || err,
    status
  }) : resolve(body));
```
Then your `action.status` should be defined in your reducer.

**Comment by nicolabortignon** [comment]
Oh perfect I see what you mean, not sure if this maybe can be a good
implementation by default.
